name: Publish Website

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate Content
      run: |
        make clean
        make html
    - name: Publish
      run: |
        remote_repo="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        remote_branch=${GH_PAGES_BRANCH:=gh-pages}
        git init
        git remote add output "$remote_repo"
        git checkout $remote_branch || git checkout --orphan $remote_branch
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        echo -n 'Files to Commit:' && ls -l | wc -l
        timestamp=$(date +%s%3N)
        git commit -m "[ci skip] Automated deployment to GitHub Pages on $timestamp"
        git push output $remote_branch --force
        rm -fr .git
